# Generated by Django 4.1.3 on 2022-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('urgent_count', models.SmallIntegerField(blank=True, null=True)),
                ('urgent_time', models.FloatField(blank=True, null=True)),
                ('high_count', models.SmallIntegerField(blank=True, null=True)),
                ('high_time', models.FloatField(blank=True, null=True)),
                ('normal_count', models.SmallIntegerField(blank=True, null=True)),
                ('normal_time', models.FloatField(blank=True, null=True)),
                ('low_count', models.SmallIntegerField(blank=True, null=True)),
                ('low_time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
